In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/supplement.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             188340 non-null  str
 1   Store_id       188340 non-null  int64
 2   Store_Type     188340 non-null  str
 3   Location_Type  188340 non-null  str
 4   Region_Code    188340 non-null  str
 5   Date           188340 non-null  str
 6   Holiday        188340 non-null  int64
 7   Discount       188340 non-null  str
 8   #Order         188340 non-null  int64
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), str(6)
memory usage: 14.4 MB

In [5]:
df.head()

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,Yes,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,Yes,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,Yes,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,Yes,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,Yes,62,45614.52

In [6]:
df.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [7]:
df.describe()

            Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [8]:
import plotly.express as px

In [9]:
pie = df["Store_Type"].value_counts().reset_index()
pie.columns = ["Store_Type", "Count"]

fig = px.pie(
    pie,
    values="Count",
    names="Store_Type"
)
fig.show()

In [10]:
pie = df["Location_Type"].value_counts().reset_index()
pie.columns = ["Location_Type", "Count"]

fig = px.pie(
    pie,
    values="Count",
    names="Location_Type"
)

fig.show()

In [11]:
import plotly.express as px

pie3 = df["Discount"].value_counts()

fig = px.pie(
    values=pie3.values,
    names=pie3.index
)

fig.show()

In [12]:
df["Discount"] = df["Discount"].map({"No": 0, "Yes": 1})

In [13]:
df

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,S1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,S4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,S3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,S2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,S2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,S2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,S4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,S1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,S3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,S2,L1,R1,2019-05-31,1,0,47,37977.00

In [14]:
df["Store_Type"] = df["Store_Type"].map({"S1": 1, "S2": 2, "S3": 3,"S4": 4})

In [15]:
df

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,L3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,L2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,L2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,L3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,L3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,L3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,L2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,L3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,L1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,L1,R1,2019-05-31,1,0,47,37977.00

In [16]:
df["Location_Type"] = df["Location_Type"].map({"L1": 1, "L2": 2, "L3": 3,"L4": 4,"L5": 5})

In [17]:
df

,ID,Store_id,Store_Type,Location_Type,Region_Code,Date,Holiday,Discount,#Order,Sales
0,T1000001,1,1,3,R1,2018-01-01,1,1,9,7011.84
1,T1000002,253,4,2,R1,2018-01-01,1,1,60,51789.12
2,T1000003,252,3,2,R1,2018-01-01,1,1,42,36868.20
3,T1000004,251,2,3,R1,2018-01-01,1,1,23,19715.16
4,T1000005,250,2,3,R4,2018-01-01,1,1,62,45614.52
...,...,...,...,...,...,...,...,...,...,...
188335,T1188336,149,2,3,R2,2019-05-31,1,1,51,37272.00
188336,T1188337,153,4,2,R1,2019-05-31,1,0,90,54572.64
188337,T1188338,154,1,3,R2,2019-05-31,1,0,56,31624.56
188338,T1188339,155,3,1,R2,2019-05-31,1,1,70,49162.41
188339,T1188340,152,2,1,R1,2019-05-31,1,0,47,37977.00

In [18]:
X = np.array(df[["Store_Type", "Location_Type", "Holiday", "Discount"]])
y = np.array(df["#Order"])

In [19]:
X

array([[1, 3, 1, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 1],
       ...,
       [1, 3, 1, 0],
       [3, 1, 1, 1],
       [2, 1, 1, 0]], shape=(188340, 4))

In [20]:
y

array([ 9, 60, 42, ..., 56, 70, 47], shape=(188340,))

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
len(X_train)

150672

In [27]:
# pip install lightgbm
import lightgbm as ltb

model = ltb.LGBMRegressor()

In [28]:
model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001783 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 15
[LightGBM] [Info] Number of data points in the train set: 150672, number of used features: 4
[LightGBM] [Info] Start training from score 68.163401

LGBMRegressor()

In [29]:
y_pred = model.predict(X_test)

c:\Users\Harsh\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [30]:
y_pred

array([47.35189701, 97.06871721, 66.57778822, ..., 47.35189701,
       61.74938636, 85.34103853], shape=(37668,))

In [31]:
data = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})

In [32]:
data

       Predicted Orders
0             47.351897
1             97.068717
2             66.577788
3             85.143083
4             54.451098
...                 ...
37663         66.577788
37664         47.722874
37665         47.351897
37666         61.749386
37667         85.341039

[37668 rows x 1 columns]